# Generated by Django 6.1 on 2026-08-28 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending on-chain confirmation'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('salt', models.CharField(max_length=64)),
                ('onchain_agreement_id', models.CharField(blank=True, default='', max_length=64)),
                ('onchain_tx_hash', models.CharField(blank=True, default='', max_length=128)),
                ('disputed', models.BooleanField(default=False)),
                ('encrypted_amount', models.TextField()),
                ('encrypted_item_description', models.TextField()),
                ('encrypted_merchant_display_name', models.TextField()),
                ('encrypted_installments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='merchants.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_index', models.PositiveSmallIntegerField()),
                ('encrypted_amount', models.TextField()),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('on_time', models.BooleanField(blank=True, null=True)),
                ('onchain_tx_hash', models.CharField(blank=True, default='', max_length=128)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='agreements.agreement')),
            ],
            options={
                'ordering': ['installment_index'],
                'unique_together': {('agreement', 'installment_index')},
            },
        ),
    ]
