# Generated by Django 6.1 on 2026-08-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='onchain_close_tx_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='agreement',
            name='onchain_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
